---
baseurl: "https://nathanleclaire.com"
title: "nathan leclaire"
layoutdir: "layouts"
contentdir: "content"
publishdir: "public"
indexes:
    category: "categories"
permalinks:
    post: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
---
